function exportGPSCSV(gps, folder)

if ~isfolder(folder)
    mkdir(folder);
end

T_gps = table( ...
    gps.t(:), ...
    gps.latitude(:), ...
    gps.longitude(:), ...
    gps.altitude(:), ...
    gps.accuracy(:), ...
    gps.bearing(:), ...
    gps.speed(:), ...
    'VariableNames', {'time','latitude','longitude','altitude','accuracy','bearing','speed'});

writetable(T_gps, fullfile(folder, "gps.csv"));

end