function exportTurnDetection(Turndetection, folder, baseName)

    if nargin < 2 || isempty(folder)
        folder = pwd;
    end

    if nargin < 3 || isempty(baseName)
        baseName = 'Turndetection';
    end

    if ~exist(folder, 'dir')
        mkdir(folder);
    end

    % -------------------------------------------------
    % 1) main peaks CSV: idx, tPeaks, values, side
    % -------------------------------------------------
    if isfield(Turndetection, 'idx') && ...
       isfield(Turndetection, 'tPeaks') && ...
       isfield(Turndetection, 'values')

        Tpeaks = table( ...
            Turndetection.idx(:), ...
            Turndetection.tPeaks(:), ...
            Turndetection.values(:), ...
            'VariableNames', {'idx', 'tPeaks', 'values'});

        if isfield(Turndetection, 'side') && ~isempty(Turndetection.side)
            Tpeaks.side = string(Turndetection.side(:));
        end

        writetable(Tpeaks, fullfile(folder, [baseName '_peaks.csv']));
    end

    % -------------------------------------------------
    % 2) intervals CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'intervals') && ...
       isfield(Turndetection.intervals, 'idx') && ...
       isfield(Turndetection.intervals, 't') && ...
       ~isempty(Turndetection.intervals.idx)

        Tintervals = table( ...
            Turndetection.intervals.idx(:,1), ...
            Turndetection.intervals.idx(:,2), ...
            Turndetection.intervals.t(:,1), ...
            Turndetection.intervals.t(:,2), ...
            'VariableNames', {'idxStart', 'idxStop', 'tStart', 'tStop'});

        if isfield(Turndetection.intervals, 'countPeaks') && ~isempty(Turndetection.intervals.countPeaks)
            Tintervals.countPeaks = Turndetection.intervals.countPeaks(:);
        end

        writetable(Tintervals, fullfile(folder, [baseName '_intervals.csv']));
    end

    % -------------------------------------------------
    % 3) left peaks CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'peaks') && ...
       isfield(Turndetection.peaks, 'left') && ...
       isfield(Turndetection.peaks.left, 'idx') && ...
       isfield(Turndetection.peaks.left, 'tPeaks') && ...
       isfield(Turndetection.peaks.left, 'values')

        Tleft = table( ...
            Turndetection.peaks.left.idx(:), ...
            Turndetection.peaks.left.tPeaks(:), ...
            Turndetection.peaks.left.values(:), ...
            'VariableNames', {'idx', 'tPeaks', 'values'});

        writetable(Tleft, fullfile(folder, [baseName '_left_peaks.csv']));
    end

    % -------------------------------------------------
    % 4) right peaks CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'peaks') && ...
       isfield(Turndetection.peaks, 'right') && ...
       isfield(Turndetection.peaks.right, 'idx') && ...
       isfield(Turndetection.peaks.right, 'tPeaks') && ...
       isfield(Turndetection.peaks.right, 'values')

        Tright = table( ...
            Turndetection.peaks.right.idx(:), ...
            Turndetection.peaks.right.tPeaks(:), ...
            Turndetection.peaks.right.values(:), ...
            'VariableNames', {'idx', 'tPeaks', 'values'});

        writetable(Tright, fullfile(folder, [baseName '_right_peaks.csv']));
    end

    % -------------------------------------------------
    % 5) average peaks CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'peaks') && ...
       isfield(Turndetection.peaks, 'avg') && ...
       isfield(Turndetection.peaks.avg, 'idx') && ...
       isfield(Turndetection.peaks.avg, 'tPeaks') && ...
       isfield(Turndetection.peaks.avg, 'values')

        Tavg = table( ...
            Turndetection.peaks.avg.idx(:), ...
            Turndetection.peaks.avg.tPeaks(:), ...
            Turndetection.peaks.avg.values(:), ...
            'VariableNames', {'idx', 'tPeaks', 'values'});

        writetable(Tavg, fullfile(folder, [baseName '_avg_peaks.csv']));
    end

    % -------------------------------------------------
    % 6) average Euler CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'averageEuler') && ...
       ~isempty(Turndetection.averageEuler) && ...
       size(Turndetection.averageEuler,2) >= 3

        TavgEuler = array2table( ...
            Turndetection.averageEuler(:,1:3), ...
            'VariableNames', {'roll_deg', 'pitch_deg', 'yaw_deg'});

        writetable(TavgEuler, fullfile(folder, [baseName '_average_euler.csv']));
    end

    % -------------------------------------------------
    % 7) average gyro CSV
    % -------------------------------------------------
    if isfield(Turndetection, 'averageGyro') && ...
       ~isempty(Turndetection.averageGyro) && ...
       size(Turndetection.averageGyro,2) >= 3

        TavgGyro = array2table( ...
            Turndetection.averageGyro(:,1:3), ...
            'VariableNames', {'gyroX', 'gyroY', 'gyroZ'});

        writetable(TavgGyro, fullfile(folder, [baseName '_average_gyro.csv']));
    end

end